# Site settings
baseurl = "https://victoramartinez.com/"
themesDir = "./themes"
title = "Victor A Martinez's Blog"
theme = "hello-friend-ng"
pagination.pagerSize = 5
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-110221350-2"
# Disable comments by leaving disqusShortname empty
disqusShortname = "vams"
publishDir = "docs"
languageCode = "en-us"

ignoreLogs = ['warning-goldmark-raw-html']


[params]
dateform = "Jan 2, 2006"
dateformShort = "Jan 2"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04 -0700"

disableReadOtherPosts = true

description = "My personal bliki"
keywords = "blog, homepage, technology, go, tech, golang, opinion"
images = [""]

contentTypeName = "content/posts"
defaultTheme = "dark"

[languages]
[languages.en]
title = "Victor's Blog"
subtitle = "Ramblings of a Software Professional"
keywords = "blog, victor, personal, wiki, bliki, opinions"
copyright = "Victor Martínez"
readOtherPosts = "Read other posts"
[languages.en.params.logo]
logoText = "echo \"Hey!\""
logoHomeLink = "/"

[social]
twitter = "https://www.twitter.com/vectorhacker"
github = "https://www.github.com/vectorhacker"
envelope = "mailto:hello@victoramartinez.com"
stack-overflow = "https://stackoverflow.com/users/2422918/victor-martinez"
telegram = "https://t.me/vectorhacker"
reddit = "https://www.reddit.com/user/vectorhacker/"

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts"
