# Site settings
baseurl = "https://victoramartinez.com/"
themesDir = "./themes"
languageCode = "en-us"
title = "Victor A. Martinez"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = "vams"
publishDir = "docs"

[params]
	name = "Victor A. Martinez"
	description = "Personal site where I post my thoughts and ideas and showcase my work."
	bio = "Software Engineer"
	# Enter optionally your twitter account
	twitter = "vectorhacker"
	enableRSS = false 

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = ["css/override.css"]
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "I'm a software engineer and computer scientist."
	tweet = ""
	share = ""
	# 404 page
	title404 = "Well this is embarrassing."
	subtitle404 = "Looks like something's missing, here I'm sorry."

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
   socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/vectorhacker"
    github   = "https://www.github.com/vectorhacker"
		linkedin = "https://www.linkedin.com/in/vectorhacker"
		envelope = "mailto:hello@victoramartinez.com"
		stack-overflow = "https://stackoverflow.com/users/2422918/victor-martinez"
		telegram  = "https://t.me/vectorhacker"
		skype = "https://join.skype.com/invite/I1vfVu1WrCr2"
		reddit = "https://www.reddit.com/user/vectorhacker/"

[[menu.main]]
	name = "About Me"
	url = "/about/"

# [[menu.main]]
# 	name = "There Ought To Be A Law..."
# 	url = "/totbal/"
# 	weight = 1